"""Create game model

Revision ID: 99a0a07dea0c
Revises: c8aadab221bf
Create Date: 2024-02-19 21:00:42.136756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a0a07dea0c'
down_revision = 'c8aadab221bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pgn', sa.String(), nullable=False),
    sa.Column('white_player_id', sa.Integer(), nullable=True),
    sa.Column('black_player_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['players.id'], name=op.f('fk_games_black_player_id_players')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_games_user_id_users')),
    sa.ForeignKeyConstraint(['white_player_id'], ['players.id'], name=op.f('fk_games_white_player_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
